[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-presence = "0.5.14"
serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.95"
ureq = "2.6.2"
